# Generated by Django 5.2.1 on 2025-05-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('related_interests', models.TextField(help_text='Comma-separated interests')),
                ('required_skills', models.TextField(help_text='Comma-separated skills')),
            ],
        ),
    ]
