# Generated by Django 5.2.1 on 2025-05-29 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0002_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='careersurvey',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 29, 13, 50, 0, 433607, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
